export const sampleLessons = [
  {
    id: "1",
    title: "Failure is Just Feedback",
    description:
      "I used to fear failing at work, until I realized every mistake was just data telling me what to fix next.",
    category: "Career",
    emotionalTone: "Realization",
    accessLevel: "Free",
    visibility: "Public",
    isFeatured: true,
    image: "https://picsum.photos/seed/lesson1/600/400",
    creator: { name: "Rafiul Islam", photo: "https://i.pravatar.cc/150?img=12" },
    createdAt: "2025-05-12",
    likesCount: 1240,
    favoritesCount: 342,
  },
  {
    id: "2",
    title: "Letting Go of People Who Drain You",
    description:
      "Not every relationship deserves your energy. Walking away can be the most loving thing you do for yourself.",
    category: "Relationships",
    emotionalTone: "Gratitude",
    accessLevel: "Premium",
    visibility: "Public",
    isFeatured: true,
    image: "https://picsum.photos/seed/lesson2/600/400",
    creator: { name: "Nusrat Jahan", photo: "https://i.pravatar.cc/150?img=32" },
    createdAt: "2025-06-02",
    likesCount: 980,
    favoritesCount: 521,
  },
  {
    id: "3",
    title: "Small Habits Build Big Lives",
    description:
      "I didn't change overnight. I changed one tiny 10-minute habit at a time, repeated for 2 years.",
    category: "Personal Growth",
    emotionalTone: "Motivational",
    accessLevel: "Free",
    visibility: "Public",
    isFeatured: true,
    image: "https://picsum.photos/seed/lesson3/600/400",
    creator: { name: "Tanvir Ahmed", photo: "https://i.pravatar.cc/150?img=51" },
    createdAt: "2025-04-21",
    likesCount: 2103,
    favoritesCount: 689,
  },
  {
    id: "4",
    title: "Grief Taught Me to Live Slower",
    description:
      "After losing my father, I stopped rushing through life. Every ordinary Tuesday became something to cherish.",
    category: "Mindset",
    emotionalTone: "Sad",
    accessLevel: "Free",
    visibility: "Public",
    isFeatured: false,
    image: "https://picsum.photos/seed/lesson4/600/400",
    creator: { name: "Sadia Rahman", photo: "https://i.pravatar.cc/150?img=44" },
    createdAt: "2025-03-10",
    likesCount: 754,
    favoritesCount: 410,
  },
  {
    id: "5",
    title: "The Job I Didn't Get Saved My Career",
    description:
      "Rejection redirected me toward a path I never planned, and it turned out to be exactly where I belonged.",
    category: "Mistakes Learned",
    emotionalTone: "Realization",
    accessLevel: "Premium",
    visibility: "Public",
    isFeatured: false,
    image: "https://picsum.photos/seed/lesson5/600/400",
    creator: { name: "Rafiul Islam", photo: "https://i.pravatar.cc/150?img=12" },
    createdAt: "2025-06-15",
    likesCount: 612,
    favoritesCount: 590,
  },
  {
    id: "6",
    title: "Boundaries Are Not Selfish",
    description:
      "Saying no used to feel like betrayal. Now I know it's the only way I show up fully for the people I love.",
    category: "Relationships",
    emotionalTone: "Motivational",
    accessLevel: "Free",
    visibility: "Public",
    isFeatured: false,
    image: "https://picsum.photos/seed/lesson6/600/400",
    creator: { name: "Nusrat Jahan", photo: "https://i.pravatar.cc/150?img=32" },
    createdAt: "2025-05-29",
    likesCount: 1340,
    favoritesCount: 455,
  },
];

export const topContributors = [
  { id: "u1", name: "Rafiul Islam", photo: "https://i.pravatar.cc/150?img=12", lessonsCount: 18 },
  { id: "u2", name: "Nusrat Jahan", photo: "https://i.pravatar.cc/150?img=32", lessonsCount: 15 },
  { id: "u3", name: "Tanvir Ahmed", photo: "https://i.pravatar.cc/150?img=51", lessonsCount: 12 },
  { id: "u4", name: "Sadia Rahman", photo: "https://i.pravatar.cc/150?img=44", lessonsCount: 9 },
];